[package]
name = "rui-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
rui-util = { path = "../rui-util" }
rui = { path = "../rui" }
